/* Relatório A4 local para os planejamentos das aeronaves. */
(function(){
'use strict';
const W=1240,H=1754,M=76,R=W-M,B=1625,enc=new TextEncoder();
async function exportReport(data){
 const pages=[];let canvas,ctx,y;
 const font=(s=23,b=false)=>ctx.font=`${b?'700':'400'} ${s}px Arial,sans-serif`;
 const text=(v,x,yy,s=23,c='#172126',b=false)=>{font(s,b);ctx.fillStyle=c;ctx.fillText(String(v??'—'),x,yy)};
 function start(subtitle='PLANEJAMENTO DE VOO'){canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#172126';ctx.fillRect(0,0,W,145);ctx.fillStyle='#078dd1';ctx.fillRect(0,140,W,5);text('IV-PLANNER',M,64,26,'#55caff',true);text(`Plano de voo • ${data.aircraft}`,M,112,38,'#fff',true);text(subtitle,M,169,17,'#58646c',true);text(new Date().toLocaleString('pt-BR'),R-245,169,17,'#58646c');y=207}
 async function finish(){ctx.strokeStyle='#d5dce0';ctx.beginPath();ctx.moveTo(M,1685);ctx.lineTo(R,1685);ctx.stroke();text('IV-PLANNER  •  Planejamento de voo',M,1715,18,'#58646c');text(`Página ${pages.length+1}`,R-110,1715,18,'#58646c');const blob=await new Promise((ok,no)=>canvas.toBlob(v=>v?ok(v):no(Error('Falha ao montar página')),'image/jpeg',.87));pages.push(new Uint8Array(await blob.arrayBuffer()));canvas.width=0}
 function wrap(value,width,size=22){font(size);const out=[];let row='';for(let word of String(value??'—').split(/\s+/)){while(ctx.measureText(word).width>width){let n=1;while(n<word.length&&ctx.measureText(word.slice(0,n+1)).width<=width)n++;if(row){out.push(row);row=''}out.push(word.slice(0,n));word=word.slice(n)}const next=row?`${row} ${word}`:word;if(row&&ctx.measureText(next).width>width){out.push(row);row=word}else row=next}if(row)out.push(row);return out.length?out:['—']}
 function heading(label,sub=''){text(label,M,y,33,'#172126',true);if(sub)text(sub,M,y+29,18,'#58646c');y+=sub?54:42}
 function rounded(x,yy,w,h,fill='#f0f3f5',stroke=null,r=18){ctx.beginPath();ctx.roundRect(x,yy,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
 function metrics(items,columns=3){const gap=12,w=(R-M-gap*(columns-1))/columns;for(let i=0;i<items.length;i+=columns){const chunk=items.slice(i,i+columns),h=97;chunk.forEach(([label,value],j)=>{const x=M+j*(w+gap);rounded(x,y,w,h,'#f0f3f5');text(label.toUpperCase(),x+14,y+25,15,'#58646c',true);font(26,true);let valueText=String(value??'—');while(valueText.length>3&&ctx.measureText(valueText).width>w-28)valueText=valueText.slice(0,-2)+'…';text(valueText,x+14,y+62,26,'#172126',true)});y+=h+12}}
 function rows(items){for(const [label,value] of items){const lines=wrap(value,R-M-36,22),h=34+31*lines.length;rounded(M,y,R-M,h,'#f0f3f5');text(label.toUpperCase(),M+17,y+23,16,'#58646c',true);lines.forEach((line,i)=>text(line,M+18,y+53+i*31,22));y+=h+9}}
 async function totalsPage(){start('RESUMO GERAL');heading('Números totais do voo','Planejamento consolidado');metrics(data.totals.metrics,3);heading('Rota planejada',data.totals.route);rounded(M,y,R-M,70,'#e8f4fb','#a9d8ed');text(data.totals.route,M+18,y+43,24,'#075b8f',true);y+=93;heading('Pesos e carga');rows(data.totals.weights);heading('Verificações');rows(data.totals.checks);await finish()}
 async function legPage(leg,isAlternate=false){start(isAlternate?'ALTERNATIVA':'ETAPA DE VOO');heading(isAlternate?'Alternativa':'Etapa '+leg.number,leg.type);rounded(M,y,R-M,185,'#172126');text(leg.route,M+28,y+58,39,'#fff',true);text(leg.airports,M+28,y+92,20,'#a8d4ec');text(isAlternate?'TRECHO PARA A ALTERNATIVA':'TRECHO PLANEJADO',M+28,y+143,16,'#55caff',true);y+=212;heading('Dados do trecho');metrics([['Distância',leg.distance],['TEV',leg.time],['Nível',leg.level],['Consumo',leg.burn],['Fuel início',leg.fuelStart],['Fuel fim',leg.fuelEnd]],3);heading('Pesos estimados');metrics([['TOW início',leg.weightStart],['Peso fim',leg.weightEnd],['ZFW',leg.zfw]],3);if(leg.note){heading('Observação');rows([['Informação',leg.note]])}await finish()}
 async function weatherPages(){
   async function weatherRows(items){for(const [label,value] of items){const lines=wrap(value,R-M-36,22),h=34+31*lines.length;if(y+h>B){await finish();start('METEOROLOGIA • CONTINUAÇÃO')}rounded(M,y,R-M,h,'#f0f3f5');text(label.toUpperCase(),M+17,y+23,16,'#58646c',true);lines.forEach((line,i)=>text(line,M+18,y+53+i*31,22));y+=h+9}}
   start('METEOROLOGIA');heading('Meteorologia do planejamento','Boletins e condições usadas nos cálculos');
   if(!data.weather.length){rows([['Boletins','Não há aeródromos definidos no planejamento.']])}
   for(const wx of data.weather){if(y>1050){await finish();start('METEOROLOGIA • CONTINUAÇÃO')}rounded(M,y,R-M,45,'#172126',null,12);text(`${wx.label} • ${wx.icao}`,M+16,y+31,21,'#fff',true);y+=60;await weatherRows([['Aeródromo',wx.airport],['Condições usadas',wx.conditions],['Cabeceira / componente',wx.runway],['Performance',wx.performance],['METAR completo',wx.metar],['TAF completo',wx.taf]]);y+=10}await finish()
 }
 await totalsPage();for(const leg of data.legs)await legPage(leg);await legPage(data.alternate,true);await weatherPages();
 const objects=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,i)=>`${4+i*3} 0 R`).join(' ')}] /Count ${pages.length} >>`,'<< /Producer (IV-PLANNER) >>'];pages.forEach((jpeg,i)=>{const page=4+i*3,image=page+1,content=page+2,cmd=`q 595 0 0 842 0 0 cm /Im${i} Do Q`;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im${i} ${image} 0 R >> >> /Contents ${content} 0 R >>`,{head:`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`,body:jpeg},`<< /Length ${enc.encode(cmd).length} >>\nstream\n${cmd}\nendstream`)});
 const parts=[enc.encode('%PDF-1.4\n')],offsets=[0];let at=parts[0].length;objects.forEach((o,i)=>{offsets.push(at);const h=enc.encode(`${i+1} 0 obj\n`);parts.push(h);at+=h.length;if(typeof o==='string'){const b=enc.encode(`${o}\nendobj\n`);parts.push(b);at+=b.length}else{const before=enc.encode(o.head),after=enc.encode('\nendstream\nendobj\n');parts.push(before,o.body,after);at+=before.length+o.body.length+after.length}});const trailer=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R /Info 3 0 R >>\nstartxref\n${at}\n%%EOF`;const blob=new Blob([...parts,enc.encode(trailer)],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`IV-PLANNER-PLANO-${data.aircraft.replace(/[^a-zA-Z0-9-]/g,'-')}.pdf`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)
}
window.IVFlightReport={exportReport};
})();
